---
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - java

- name: Add Jenkins repository
  get_url: 
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644
    
- name: Add Jenkins repository key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    
